[package]
name = "bsa"
version = "0.1.0"
edition = "2018"


[dependencies]
enumflags2 = "0.7.1"
structopt = "0.3"
bytemuck = { version = "1.5.1", features = ["derive"] }
lz4 = "1.23.2"
glob = "0.3.0"
libflate = "1.1.0"

[lib]
name = "bsa"
path = "src/bsa/lib.rs"
