[package]
name = "bsabin"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "bsa"
path = "src/main.rs"

[dependencies]
clap = "3.0.0-beta.4"
glob = "0.3.0"
bsa = { version = "0.1.0", path = "../bsa" }
